// signalFromHardware.cpp

// Demonstrates the registration of signal and signal handler
// Signal is generated by the hardware

#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <iostream>
using std::cout;

// Define the handler function to be called when SIGFPE(8) is generated by the hardware on floating point exception
void sigfpe_handler(int signum)
{
   // Write the code here that this handler is supposed to do
   printf("Signal %d caught.\n", signum);
   cout << "Exiting the program.\n";   
   // Terminate program
   exit(signum);
}

int main()
{
   	// Register the signal we are interested in and its signal handler
   	signal(SIGFPE, sigfpe_handler);

	int x = 5, y = 0;
	int z = x/y;
    
	return(EXIT_SUCCESS);
}          
